{% set name = "joserfc" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/joserfc-{{ version }}.tar.gz
  sha256: eebca7f587b1761ce43a98ffd5327f2b600b9aa5bb0a77b947687f503ad43bc0

build:
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
    - wheel
  run:
    - python
    - cryptography

test:
  source_files: 
    - tests
  imports:
    - joserfc
  commands:
    - pip check
    - pytest -vv
  requires:
    - pip
    - pytest
    - pycryptodome

about:
  home: https://jose.authlib.org/en/dev/
  summary: Implementations of JOSE RFCs in Python
  description: |
    joserfc is a Python library that provides a comprehensive implementation of several essential JSON Object Signing and Encryption (JOSE) standards.
  dev_url: https://github.com/authlib/joserfc
  doc_url: https://jose.authlib.org/en/dev/
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - jan-janssen
