{% set name = "joserfc" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e8c2f327bf10a937d284d57e9f8aec385381e5e5850469b50a7dade1aba59759

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - cryptography

test:
  source_files: 
    - tests
  imports:
    - joserfc
  commands:
    - pip check
    - pytest -vv
  requires:
    - pip
    - pytest
    - pycryptodome

about:
  home: https://jose.authlib.org
  summary: Implementations of JOSE RFCs in Python
  description: |
    joserfc is a Python library that provides a comprehensive implementation of several essential JSON Object Signing and Encryption (JOSE) standards.
  dev_url: https://github.com/authlib/joserfc
  doc_url: https://jose.authlib.org
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD

extra:
  recipe-maintainers:
    - jan-janssen
